### ISSUE TITLE
Unsupported os.name: SunOS

### ISSUE THREAD

**Issue by whittlec** [cmake-maven-project/cmake-maven-project#12]
The Maven plugin fails when executed on a platform it does not recognize.

It should only fail when asked to download the binaries for a platform it does not recognize. If using native CMake already on the system it should continue and use those.

**Comment by ksclarke** [comment]
The "download.cmake=false" is really only for Raspberry Pis at this point. It hasn't been testing (or promoted) for any of the existing (or other, like SunOS) platforms yet.

I figured there would be an interest in seeing it work for others though too.

**Comment by silverjam** [comment]
FYI, `download.cmake=false` worked for me building inside a container based
on Alpine.

**Comment by cowwoc** [comment]
@whittlec does `download.cmake=false` work for you? If not, can you please provide a stack-trace for version 3.7.0-b1-SNAPSHOT?

**Comment by whittlec** [comment]
I couldn't find 3.7.0-b1-SNAPSHOT in the repository, but b2 was there so I tried that. That worked perfectly.

**Comment by cowwoc** [comment]
@whittlec Perfect, so you can use `3.7.0-b1` which is an official release. Do you consider this issue closed or are more changes necessary?

**Comment by whittlec** [comment]
Tried `3.7.0-b1` and it works too. I believe this issue can now be closed. Thanks!

**Comment by cowwoc** [comment]
Excellent. Thanks for the verification.
