### ISSUE TITLE
Rename classifiers to match os.arch

### ISSUE THREAD

**Issue by cowwoc** [cmake-maven-project/cmake-maven-project#17]
Currently cmake classifier references 32-bit Windows using `windows-i386` but the Java system property returns `x86` for this platform. As such, we should rename the classifier to `windows-x86`.

**Comment by cowwoc** [comment]
Similarly, `mac-amd64` should be renamed to `mac-x86_64`.

**Comment by ksclarke** [comment]
I've wondered about using https://github.com/trustin/os-maven-plugin to smooth out the name/property variations. Not really volunteering to do that work at the moment but would be curious to hear your thoughts on it.

**Comment by cowwoc** [comment]
Great find. I'll push a PR in a minute ;)

**Comment by cowwoc** [comment]
@ksclarke Please review https://github.com/cmake-maven-project/cmake-maven-project/pull/18

I have opted to add new platforms as we run into them (versus adding them up-front) but at least now we have a consistent naming convention for the future.

**Comment by ksclarke** [comment]
Sounds good to me, and the PR looks good to me too.

**Comment by cowwoc** [comment]
Resolved by https://github.com/cmake-maven-project/cmake-maven-project/pull/18
