### ISSUE TITLE
Cannot use -Ax64 with old maven 3.0.5

### ISSUE THREAD

**Issue by dmikushin** [cmake-maven-project/cmake-maven-project#20]
```
[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.7.2-b1:generate (cmake-generate) on project MorphoLibJ_: Unable to parse configuration of mojo com.googlecode.cmake-maven-project:cmake-maven-plugin:3.7.2-b1:generate for parameter options: Cannot assign configuration entry 'options' with value '-Ax64' of type java.lang.String to property of type java.util.List -> [Help 1]
```

Does not happen, if newer maven is used, e.g. 3.3.9 as described here: https://github.com/kongchen/swagger-maven-plugin/issues/441

Any idea how to make `cmake.options` compatible with older versions of maven?

**Comment by cowwoc** [comment]
Hi @dmikushin,

Are you saying that you are unable to upgrade to a newer version of Maven? I believe version 3.5.0 is out by now.

**Comment by dmikushin** [comment]
Hi @cowwoc,

I'm surely able, however older versions are still around (e.g. Ubuntu 14.04 's default maven is 3.0). I'd love to propose a patch myself, but there seems to be no trivial way expand `cmake.options` according with List syntax, since `cmake.options` is already a member of upper-level List.

**Comment by dmikushin** [comment]
Oh, I've tried that one yesterday, but somehow `cmake.options` error takes priority over maven version check.

**Comment by cowwoc** [comment]
@dmikushin I just committed an update to the `master` branch. Try building that locally then build your application against it. When I ran this test on my end, the build failed with the expected error:

```
Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.7.2-b2-SNAPSHOT:generate (cmake-generate) on project TESTCASE: The plugin com.googlecode.cmake-maven-project:cmake-maven-plugin:3.7.2-b2-SNAPSHOT requires Maven version 3.3.9 -> [Help 1]
```

**Comment by dmikushin** [comment]
@cowwoc Thanks! I will close this ticket for now then.
