### ISSUE TITLE
Create Travis build for Windows

### ISSUE THREAD

**Issue by ksclarke** [cmake-maven-project/cmake-maven-project#22]
Travis has a Windows beta but it doesn't yet support Java by default. When it does, add support for a Windows build on Travis.

**Comment by cowwoc** [comment]
@ksclarke Just a thought: we could treat Java the same way we do the Maven wrapper: wget the OpenJDK binaries, add them to our path, and run. That's essentially what I do under my local Windows machine nowadays since OpenJDK for Windows does not com with an installer.

**Comment by ksclarke** [comment]
That seems more like what I was doing without Maven wrapper. You convinced me it'd be better to use Maven wrapper because there would be less upkeep. I think waiting for Travis to add it would also provide less upkeep, rather than us having to keep the OpenJDK up to date. If there is a plugin that works like Maven wrapper... OpenJDK wrapper(?)... I'm open to that, though. We'd have to set the Travis config languate to "bash" though so it would impact all the builds, not just the Windows one (which seems less than desirable to me).

**Comment by cowwoc** [comment]
You're right. Let's just wait for Travis to catch up. I'll keep on using my private Jenkins cluster at home to make Windows releases. One day Travis will take over :)

**Comment by cowwoc** [comment]
Fixed by https://github.com/cmake-maven-project/cmake-maven-project/pull/38
