### ISSUE TITLE
Locate cmake on $PATH

### ISSUE THREAD

**Issue by tresf** [cmake-maven-project/cmake-maven-project#23]
Enhancement request to find `cmake` on `$PATH`, rather than hard-coding it per-configuration.  For example, on Windows, it could be a localized install, or a system-wide install, but to use `cmake` from command line, a developer would generally have it on `$PATH` so it can be called easily.

Examples:
* Windows `CMake` desktop installer adds to `%PATH%`
* macOS's Homebrew adds `cmake` to `/usr/local/bin` which is already in `$PATH`
* (Obviously) Linuxes add `cmake` (usually to `/usr/bin` which is on `$PATH`)

As a temporary workaround, a developer can provide:

```xml
<!-- Windows -->
<cmake.root.dir>${env.PROGRAMFILES}/CMake</cmake.root.dir>
<cmake.child.dir>bin/cmake.exe</cmake.child.dir>

<!-- MacOS -->
<cmake.root.dir>/usr/local/</cmake.root.dir>
```

... but on most developer machines, these setting would already be obvious/redundant with the system.

**Comment by cowwoc** [comment]
Should be fixed by https://github.com/cmake-maven-project/cmake-maven-project/pull/31

**Comment by tresf** [comment]
@cowwoc thanks kindly.  I've since moved to another, manual technique to invoke `cmake` from maven so I'm afraid I won't be testing this in the near future and for that I'm sorry.

**Comment by cowwoc** [comment]
No worries.
