### ISSUE TITLE
Cutting edge Maven required

### ISSUE THREAD

**Issue by hoditohod** [cmake-maven-project/cmake-maven-project#28]
Hi,
The latest release requires a quite new Maven (3.6.1) and as I see this requirement is even stricter in newer commits. The prev release (3.7.2-b1) didn't have a version requirement on Maven itself.

Is cutting edge really necessary? DevOps in my organization prefers the distro bundled maven version, and they don't like the idea of installing a newer Maven for just this plugin...

**Comment by cowwoc** [comment]
It's not strictly required but it made our lives easier. Which version are you asking for? All tools I've used have updated their bundled version to 3.6.1.

**Comment by hoditohod** [comment]
Ubuntu 18.04 LTS currently ships Maven 3.6.0. I think that would be a fairly conservative dependency, that would make this plugin available out of the box for a lot of people.

**Comment by cowwoc** [comment]
I pushed https://github.com/cmake-maven-project/cmake-maven-project/commit/36ade53a573429f8719f10adbd7afd806d14ef90 but I cannot publish a formal release for another 1-2 months. The builds run on my home machine and we're renovating for the next 1-2 months so the network setup is completely different where I'm at now. Stupid I know, but there it is...

I'll let you know once this is rectified.

**Comment by cowwoc** [comment]
Hi @hoditohod 

I decided to try to push this through ahead of schedule. Can you please test `3.16.2-b2-SNAPSHOT` locally and let me know if it works for you? If so, I'll promote it to an official release.

You'll need to pull snapshot builds from oss per https://stackoverflow.com/a/16286460/14731

**Comment by cowwoc** [comment]
3.16.3-b1 has been released. It will be accessible on Maven Central in 2 hours.
