### ISSUE TITLE
Compile and test goals do not work on Windows

### ISSUE THREAD

**Issue by stephen-webb** [cmake-maven-project/cmake-maven-project#29]
When the downloadBinaries property is true, they try to run cmake/ctest instead of cmake.exe/ctest.exe.

After fixing that, the testGenerateDashboardTest test fails (org.apache.maven.it.Verifier trys to run bin/mvn)

**Comment by cowwoc** [comment]
Fixed by https://github.com/cmake-maven-project/cmake-maven-project/pull/31

**Comment by cowwoc** [comment]
3.16.3-b1 has been released. It will be accessible on Maven Central in 2 hours.
