### ISSUE TITLE
ctest needs to be told which configuration it should test

### ISSUE THREAD

**Issue by stephen-webb** [cmake-maven-project/cmake-maven-project#32]
When using a multi configuration generator like Xcode or Visual Studio.

I believe the -C flag will be ignored by single configuration generators

**Comment by cowwoc** [comment]
Fixed by https://github.com/cmake-maven-project/cmake-maven-project/pull/33

**Comment by cowwoc** [comment]
3.16.3-b1 has been released. It will be accessible on Maven Central in 2 hours.
