### ISSUE TITLE
make install 

### ISSUE THREAD

**Issue by madhavsuresh** [cmake-maven-project/cmake-maven-project#35]
Hi All, 

I want to run "make install" after running the cmake-compile goal. Is this possible with cmake-maven? I've tried setting an option "--target install" in the compile goal, however I get an error "Unknown argument --target install"

Thanks! 
Madhav

**Comment by madhavsuresh** [comment]
I figured out the issue, I had the option as 
`       <option>--target install</option>
`
It should be
`       <option>--target</option>
         <option>install</option>
`

**Comment by cowwoc** [comment]
Perfect. Glad you figured it out!
