### ISSUE TITLE
profiles and cmake-maven-plugin

### ISSUE THREAD

**Issue by kwhat** [cmake-maven-project/cmake-maven-project#36]
Is it possible to add some configuration options in a maven profile for cmake-maven-plugin? I was wondering how to pass `-Dtoolchain=<file>` in some but not all profiles.

Thanks for the plugin, it has been quite helpful.

**Comment by cowwoc** [comment]
@kwhat

1. Declare a property to an empty value globally (e.g. `<properties><cmake.options/></properties>`
2. Override its value inside specific profiles.
3. Pass the property into `<option>${cmake.options}</option>`

Let me know if this works.

**Comment by kwhat** [comment]
Seems to be a reasonable solution, didn't realize I could pass an empty variable by default.  Thanks.
