### ISSUE TITLE
Locate cmake on PATH, Windows uses "Path" not "PATH"

### ISSUE THREAD

**Issue by kwhat** [cmake-maven-project/cmake-maven-project#37]
I am seeing ` MojoExecutionException: cmake not found on PATH: null` when trying to locate cmake on the path with Windows.  I am guessing this is because Windows uses `Path` which is not equal to `PATH` at [CmakeMojo.java#L108](https://github.com/cmake-maven-project/cmake-maven-project/blob/master/cmake-maven-plugin/src/main/java/com/googlecode/cmakemavenproject/CmakeMojo.java#L108).  Wonder if `processBuilder.environment().get("PATH")` can be made case insensitive or do I need to hack my Windows Path name?

**Comment by cowwoc** [comment]
@kwhat Per http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/windows/classes/java/lang/ProcessEnvironment.java#l195 this should not be possible.

Can you please set a breakpoint at the aforementioned line and check whether you get different values for `processBuilder.environment().get("PATH")` vs `processBuilder.environment().get("Path")`?

Also, which Windows version are you using?

**Comment by kwhat** [comment]
Alright, It finally built again but I needed to do it step by step, `mvn clean compile package install` doesn't work.  I was able to conform  my suppression that "PATH" is null and the key is "Path" on Windows.

PATH: null
Path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\CMake\bin;C:\Users\vbox\AppData\Local\Microsoft\WindowsApps;C:\Java\jdk-11.0.7\bin;C:\Java\apache-maven-3.6.3\bin;

**Comment by cowwoc** [comment]
What are your Windows and JDK versions?

**Comment by kwhat** [comment]
Windows 10 LTSB: 1607 (14393.3686)
Java Version: (11.0.7) 2020-04-14 LTS
Java SE Runtime Environment: 18.9 (build 11.0.7+8-LTS)
Java HotSpot 64-Bit Server VM: 18.9 (build 11.0.7+8-LTS, mixed mode)
cmake-maven-project versions: 3.16.3-b2 & 3.16.3-b3-SNAPSHOT for test changes

**Comment by cowwoc** [comment]
@kwhat I am able to reproduce the bug. I'll get back to you shortly.

**Comment by kwhat** [comment]
@cowwoc Just tested 0aad534 and it looks good!  Everything working on Windows as expected!  Thank you.

**Comment by cowwoc** [comment]
Cool. Thank you for testing. I will publish a new release within the next couple of days.

**Comment by kwhat** [comment]
@cowwoc 

Sorry to bother you again, just wondering about the release status of this fix.  Thanks,

**Comment by cowwoc** [comment]
@kwhat Sorry. This fell through the cracks. I'll try to publish a release by the end of the week. Don't hesitate to reach out again if I forget.

**Comment by cowwoc** [comment]
@kwhat I just published 3.17.3-b1. It'll show up on Maven Central within 20 minutes.
