### ISSUE TITLE
Support for linux on 64 bit ARM?

### ISSUE THREAD

**Issue by jimfcarroll** [cmake-maven-project/cmake-maven-project#49]
I see you support mac on 64 bit arm and, though it seems strange, you interpret linux with an arch of X86_32 as being ARM in OperatingSystem.java, but there's no support for aarch64 64 bit ARM based linux. Though CMake itself runs fine there.

I was thinking about adding it and submitting a PR but I'm not sure how you package the binaries. Is it independent of building this project?

EDIT: If I'm not mistaken, you're pulling the pre-packaged binaries from a hardcoded location here: https://github.com/Kitware/CMake/releases/... Looking there I see linux aarch64 tar files.

**Comment by jimfcarroll** [comment]
PR: https://github.com/cmake-maven-project/cmake-maven-project/pull/50

**Comment by cowwoc** [comment]
You can find the Jenkins build script at https://github.com/cmake-maven-project/cmake-maven-project/blob/master/jenkins/cmake%20(release)/config.xml

We run three builds in parallel on Windows, Linux and MacOS. Each platform builds and uploads its specific binaries. Linux additionally builds and uploads the portable (Java) code.

Once all the files have been uploaded into the same container, we release it to Maven Central.

I'd like to migrate this to Github Actions but I don't have the time. Let me know if you're willing to take a look.

On the topic of this specific ticket, where in the code do you see us interpreting Linux with arch of X86_32 as being ARM?

**Comment by jimfcarroll** [comment]
I posted PR#50 that includes the aarch64 ARM architecture and it's working fine for me. The PR also contains a link to the exact line with what appears to be a misinterpretation but for completeness it's here:  https://github.com/cmake-maven-project/cmake-maven-project/blob/master/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L62

**Comment by cowwoc** [comment]
Hi @jimfcarroll 

Can you please confirm whether https://github.com/cmake-maven-project/cmake-maven-project/pull/51 fixes this issue for you?

**Comment by jimfcarroll** [comment]
Responded on PR 51 ... thanks!
