### ISSUE TITLE
Unable to find/resolve artifact linux-arm_64:3.25.2-b1

### ISSUE THREAD

**Issue by jjfumero** [cmake-maven-project/cmake-maven-project#52]
Hi, 
  I am getting the following error when using the latest version:

```bash
[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.25.2-b1:compile (cmake-compile) on project tornado-drivers-ptx-jni:
Unable to find/resolve artifact.: com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.25.2-b1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. 
This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

My current configuration:

```xml
           <groupId>com.googlecode.cmake-maven-project</groupId>
           <artifactId>cmake-maven-plugin</artifactId>
           <version>3.25.2-b1</version>
```

However, the version I was using (`3.7.0-b2`) works. Any pointers/recommendations to get the latest `cmake-maven` plugin with ARM-64 systems? Maybe I am missing something. 

For reference, I am using an NVIDIA Jetson Nano (ARMv8 Processor) and Ubuntu 18.04.6 LTS.

**Comment by cowwoc** [comment]
Can't you simply use the latest version? As you mentioned, it works...

**Comment by cowwoc** [comment]
Good catch! The latest release did not upload any arm-64 binaries. I'll try to work on this in the coming days.

**Comment by cowwoc** [comment]
Please give version 3.26.3-b1 a try. It should be in Maven Central within the hour.

**Comment by jjfumero** [comment]
Thank you @cowwoc . It works now!
