### ISSUE TITLE
Support Windows on Arm64

### ISSUE THREAD

**Issue by chrisdutz** [cmake-maven-project/cmake-maven-project#56]
I would like to be able to use cmake to compile on Windows systems (mostly VMs) that are running on Macs M1 or M2 chips.

How is this new feature useful?
I maintain many OS projects and need to be able to check the builds of these on many operating systems. Having to grab my old Mac book to start a Windows VM in order to test Windows is slightly annoying ;-)

How can this be implemented?
I don't think there is much we need to do.
When I installed the openjdk-20 on my system with chocolatey, it worked, however I noticed that the Java runtime invalidly reported to be x86_64 ... this caused cmake to download and build correctly on Windows aarch64 ... it produced executables that worked nicely on that system, but when trying to use the binaries compiled on that system on a x86_64 system, I got "wrong architecture" errors.

When I updated the JDK to one that correctly reports the os.arch, the build started failing.

So I think it might be super easy to support building on aarch64 windows machines, as generally already should work and we're just giving up early here:
https://github.com/cmake-maven-project/cmake-maven-project/blob/7e7929d1330f53cb8d7c1768784ef1acc680a2f8/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L74

**Comment by cowwoc** [comment]
Agreed. This should be easy to fix. 

> I noticed that the Java runtime invalidly reported to be x86_64 ... this caused cmake to download and build correctly on Windows aarch64 ... it produced executables that worked nicely on that system, but when trying to use the binaries compiled on that system on a x86_64 system, I got "wrong architecture" errors.

I'd like to dig into that for a second. Correct me if I'm wrong:

* chocolatey downloads a JDK for x86_64 instead of aarch64.
* This JDK runs (why though? Shouldn't the x64 build fail to run on aarch64?) but reports the wrong architecture. 
* This plug-in downloads the x86_64 version of cmake which runs (again, this surprises me) not realizing that the Visual Studio compiler that it is invoking is actually going to output aarch64 binaries.
* If you try running this binaries under x86_64 they fail because are designed to run under aarch64.

Is that correct?

**Comment by chrisdutz** [comment]
I think chocolatey seems to download a JDK that claims to be "x86_64" ... but I do think it is an aarch64 version, as I think it would have problems running on aarch64 otherwise, right? So I guess I should probably find out which openjdk version it installs and open a PR on that project too.

Yeah ... so for some reason ... Either it downloaded the x86_64 binaries of the jdk and it correctly claimed to be x86_64 and therefore it downloaded the x86_64 binaries of cmake and for some reason these too were able to run on aarch64 ...

I guess we could try simply not aborting the build with an error and see what happens if we execute the x86_64 versions on aarch64.

**Comment by cowwoc** [comment]
I've run into a bit of a snag trying to fix this issue. I've deployed a fix to `master` but I am unable to deploy the windows ARM64 binaries because GitHub does not provide any runners for that platform. I can only deploy binaries for platforms that I can run automated builds from.

I've used https://github.com/uraimo/run-on-arch-action to deploy binaries for Linux ARM64 in spite of GitHub not providing built-in runners for that platform, but this mechanism does not support Windows ARM64.

If you can find a way to run automated GitHub builds under Windows ARM64 then I think we should be able to make this work.

**Comment by cowwoc** [comment]
I'm going to give https://github.com/actions/runner/blob/8fa970a1e695c7d2400199cede00d7dd9e76dc97/.github/workflows/release.yml#L105 a try tomorrow. Maybe we'll get lucky and it'll work.

**Comment by chrisdutz** [comment]
Isn't there an option for self-hosted runners? But admittedly no idea how to do that.

**Comment by cowwoc** [comment]
Yes, this would work on self-hosted runners but as an open-source project I'm not open to paying for these services. If you discover any free self-hosted runners for open-source projects please let me know.

I tried https://github.com/actions/runner/blob/8fa970a1e695c7d2400199cede00d7dd9e76dc97/.github/workflows/release.yml#L105 and it was a no-go. They are just cross-compiling code from Windows x86 to ARM64.

I'll give this some more thought. Maybe I can run the full build under supported platforms and for all the ARM64 platforms I will publish the cmake binaries without actually testing them out.

I'll be away on vacation on August 11th - 19th, so it's looking increasingly unlikely that I'll finish this work before I get back. But I'll try...

**Comment by cowwoc** [comment]
This issue is moving in slow motion, but at least I'm making some progress. I plan to investigate https://blogs.oracle.com/cloud-infrastructure/post/announcing-github-actions-arm-runners-for-the-arm-compute-platform-on-oracle-cloud-infrastructure next. This would be so much easier if GitHub just supported this in-house :)

**Comment by cowwoc** [comment]
Please try version 3.27.7-b1

**Comment by chrisdutz** [comment]
Ok ... tried it in one of my projects and it worked .. the executable seems to be a native windows aarch64 executalbe ... the only thing I noticed, was that in the log it was downloading something for windows-x86-64 ... but if in the end the output works, I'm fine with that ... going to test it with another project right away.

Thanks for fixing this :)

**Comment by chrisdutz** [comment]
[INFO] --- cmake:3.27.7-b1:generate (cmake-generate) @ iotdb-tools-thrift ---
[INFO] Downloading binaries to Y:\Projects\Apache\IoTDB\iotdb-bin-resources\iotdb-tools-thrift\target\dependency\cmake
[INFO] Configured Artifact: com.googlecode.cmake-maven-project:cmake-binaries:windows-x86_64:3.27.7-b1:jar

**Comment by chrisdutz** [comment]
Ok ... I found out what was going on ... all the JDKs seem to be non native aarch64 jdks, however I managed to find one build by Microsft, which is true aarch64 ... so now I'm actually having a problem: https://github.com/cmake-maven-project/cmake-maven-project/blob/master/cmake-common/src/main/java/com/googlecode/cmakemavenproject/Platform.java detexts the type as `windows-arm64.zip` and it therefore tries to download `com.googlecode.cmake-maven-project:cmake-binaries:jar:windows-arm64:3.27.7-b1` however when having a look at the name of the artifact staged it's more `com.googlecode.cmake-maven-project:cmake-binaries:jar:windows-arm_64:3.27.7-b1` with an extra slash between the arm and the 64.

So I added a dependency to the staged version and after resolving it I created a copy with the other name ... now it seems it correctly built an aarch64 binary with the correct cmake binaries and this time it even staged it with the right classifier.

**Comment by chrisdutz** [comment]
And it seems the Linux aarch64 version is now missing ...

**Comment by cowwoc** [comment]
Thanks for the feedback. I'll review the two issues you reported.

**Comment by chrisdutz** [comment]
I think simply renaming the classifier for the cmake-binaries bundle for arm 64 windows should fix the one issue and additionally staging the arm 64 version for linux should solve the other problem.

**Comment by chrisdutz** [comment]
So coming back to this issue ... now it seems that the plugin tries to download an artifact with the classifier "windows-arm64", however the binaries available are called "windows-arm_64".
https://repo1.maven.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.27.7-b1/

**Comment by chrisdutz** [comment]
Unfortunately version 3.27.7-b1 seems to be missing the arm_64 version for linux ...

**Comment by cowwoc** [comment]
It seems like I really botched this eh? :)

What artifacts do we currently output?

**Comment by chrisdutz** [comment]
Well ... I've spent friday and saturday to prepare empty systems with:
- Win x86_64
- Win amd64
- Win aarch64
- Lnx x86_64
- Lnx amd64
- Lnx aarch64
- Mac x86_64
- Mac aarch64
(There is no Mac amd64)
In order to test our installation documentation in PLC4X ... guess with that I'll also be able to collect a list of what artifacts would bee needed and what they would need to be called. I do think in the last few versions deployed there were inconsistent variants available.

**Comment by chrisdutz** [comment]
Ok ... so on Windows in a VM on aarch64 can be convinced to work, by renaming the 
https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.27.7-b1/cmake-binaries-3.27.7-b1-windows-arm_64.jar
Artifact to:
https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.27.7-b1/cmake-binaries-3.27.7-b1-windows-arm64.jar

**Comment by chrisdutz** [comment]
So I've added this to our build and it seems to be working on windows arm64 systems. Wit that I am able to build.

`
    <profile>
      <id>.os-windows-aarch64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>download-aarch64-windows-binaries</id>
                <phase>validate</phase>
                <goals>
                  <goal>copy</goal>
                </goals>
                <configuration>
                  <outputDirectory>${project.build.directory}/redeploy</outputDirectory>
                  <artifactItems>
                    <artifactItem>
                      <groupId>com.googlecode.cmake-maven-project</groupId>
                      <artifactId>cmake-binaries</artifactId>
                      <version>${cmake.version}</version>
                      <classifier>windows-arm_64</classifier>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-install-plugin</artifactId>
            <executions>
              <execution>
                <id>install-aarch64-windows-binaries</id>
                <phase>validate</phase>
                <goals>
                  <goal>install-file</goal>
                </goals>
                <configuration>
                  <file>${project.build.directory}/redeploy/cmake-binaries-${cmake.version}-windows-arm_64.jar</file>
                  <groupId>com.googlecode.cmake-maven-project</groupId>
                  <artifactId>cmake-binaries</artifactId>
                  <version>${cmake.version}</version>
                  <classifier>windows-arm64</classifier>
                  <packaging>jar</packaging>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
`

In version 3.27.7-b1 for some reason is looks as if the arm64 version of linux is missing. Strangely it is still downloading something (I would assumbe the x86_64 version) which seems to be failing when running cmake as it doesn't seem to be able to run the test-compile. I expected it to be the same problem and made the linux artifact avaialble from the official cmake website and re-deploying that locally, however the issue is still the same:

`
    
    <profile>
      <id>.os-linux-aarch64</id>
      <activation>
        <os>
          <family>linux</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.googlecode.maven-download-plugin</groupId>
            <artifactId>download-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>download-aarch64-linux-binaries</id>
                <phase>validate</phase>
                <goals>
                  <goal>wget</goal>
                </goals>
                <configuration>
                  <url>https://cmake.org/files/v3.27/cmake-3.27.7-linux-aarch64.tar.gz</url>
                  <unpack>true</unpack>
                  <outputDirectory>${project.build.directory}/redeploy</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <executions>
              <execution>
                <id>package-aarch64-linux-binaries</id>
                <phase>validate</phase>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <classesDirectory>${project.build.directory}/redeploy/cmake-3.27.7-linux-aarch64</classesDirectory>
                  <includes>
                    <include>**</include>
                  </includes>
                  <finalName>cmake-binaries-${cmake.version}-linux-arm_64</finalName>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-install-plugin</artifactId>
            <executions>
              <execution>
                <id>install-aarch64-linux-binaries</id>
                <phase>validate</phase>
                <goals>
                  <goal>install-file</goal>
                </goals>
                <configuration>
                  <file>${project.build.directory}/cmake-binaries-${cmake.version}-linux-arm_64.jar</file>
                  <groupId>com.googlecode.cmake-maven-project</groupId>
                  <artifactId>cmake-binaries</artifactId>
                  <version>${cmake.version}</version>
                  <classifier>linux-arm_64</classifier>
                  <packaging>jar</packaging>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
`

**Comment by chrisdutz** [comment]
And regarding the deployment of cmake-binaries ... wouldn't it be an option to simply re-package the files on the official cmake site? https://cmake.org/files/v3.27/

**Comment by cowwoc** [comment]
I'll try to take a look sometime this week. Thanks for the follow-up.

**Comment by cowwoc** [comment]
@chrisdutz Can you please give https://github.com/cmake-maven-project/cmake-maven-project/commit/4ea1e2cb6e2c7f28b87b2657bbb0d866d59e74e4 a try and let me know if it fixes your problems? The main change is https://github.com/cmake-maven-project/cmake-maven-project/commit/4ea1e2cb6e2c7f28b87b2657bbb0d866d59e74e4#diff-27f0a94df8f7b1849cc752b686f7bdf191fbe44ab357cb24ee0551bda7fc9002R95

**Comment by chrisdutz** [comment]
That should make things work on Windows with aarch64 cpus, a bit curious why there is no linux version for aarch64

**Comment by cowwoc** [comment]
@chrisdutz aarch64 for Linux should be `linux-arm_64` which is covered by https://github.com/cmake-maven-project/cmake-maven-project/actions/runs/9054539647/job/24874520632

This doesn't work for you?

**Comment by cowwoc** [comment]
Actually, you're right. Looking at https://github.com/cmake-maven-project/cmake-maven-project/actions/runs/9054539647/job/24874520632 it's spinning up linux-x86_64 instead of arm64 for some reason. I'll investigate.

**Comment by chrisdutz** [comment]
.Well on my system Linux + aarch64 actually doesn't work, but it's a different problem I guess. Others have reported to be able to build ... I was just wondering that there is no linux-arm_64 artifact available here: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.27.7-b1/ or is the x86_64 a "universal" one, that works on both?

**Comment by cowwoc** [comment]
I just remembered what the problem is :)

GitHub's built-in runners do not support arm64. The only solution I found is https://runs-on.com/. I got a free license for it, but then you need to run the CI on an AWS machine. And that AWS machine costs money (the free tier does not include S3 and potentially other components they use).

So we've got the following options:

1. Use a Github-based runner with an emulator that only supports linux-arm64 (drop MacOS and Windows arm64 support)
2. Find someone willing to pay for an AWS machine.
3. Only download and repackage the cmake binaries for MacOS and Windows arm64 but do not run any tests. Cross our fingers and hope this works.

I think option 3 is the one we settled on. I will try making that work now.

**Comment by chrisdutz** [comment]
And what about fetching the binaries published by the cmake folks and to re-package and re-deploy them? 
https://cmake.org/files/v3.27/
That's how I'm doing my workaround.

**Comment by cowwoc** [comment]
@chrisdutz That was rather painful, but I think I finally fixed this issue. Please try the latest version of the 3.27.7-b1 branch

**Comment by cowwoc** [comment]
Ah, nevermind. There is still one more problem left. I'll let you know when it's fixed.

**Comment by cowwoc** [comment]
@chrisdutz Please give version 3.29.3-b1 a try and let me know if I missed anything

**Comment by chrisdutz** [comment]
For windows on Arm64 I can confirm that this version works without my fix, however for Linux on arm64 the problem still persists ... I still need my workaround for downloading the arm_64 version, unpacking and locall installing it in order to be able to run the build on my Linunx VM on my M2 Mac:

```
[INFO] Configured Artifact: com.googlecode.cmake-maven-project:cmake-binaries:linux-arm_64:3.29.3-b1:jar
Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/com/googlecode/cmake-maven-project/cmake-binaries/3.29.3-b1/cmake-binaries-3.29.3-b1.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.29.3-b1/cmake-binaries-3.29.3-b1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.29.3-b1/cmake-binaries-3.29.3-b1.pom (1.5 kB at 154 kB/s)
Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/com/googlecode/cmake-maven-project/cmake-binaries/3.29.3-b1/cmake-binaries-3.29.3-b1-linux-arm_64.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.29.3-b1/cmake-binaries-3.29.3-b1-linux-arm_64.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.498 s
[INFO] Finished at: 2024-05-19T12:20:35+02:00
[INFO] ------------------------------------------------------------------------
[INFO] 12 goals, 12 executed
[INFO] Cleaning up the local build cache...
[INFO] Deleted 142 unused files from the local build cache in 0.008s
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.29.3-b1:generate (cmake-generate-test-compile) on project plc4c: Unable to find/resolve artifact.: The following artifacts could not be resolved: com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.29.3-b1 (absent): Could not find artifact com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.29.3-b1 in apache-releases (https://repository.apache.org/content/repositories/releases) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by cowwoc** [comment]
Ah, my mistake: https://github.com/cmake-maven-project/cmake-maven-project/actions/runs/9131203456 shows that I didn't even try building for Linux-arm_64. I'll let you know once a new build is ready for testing.

**Comment by chrisdutz** [comment]
Ok with CMake 3.29.3-b2 I see it's now downloading the right binary :-)

**Comment by chrisdutz** [comment]
Same on Windows Arm64 ... now testing the remaining 3 options with x86_64/amd64

**Comment by chrisdutz** [comment]
Ok ... now it's working on all platforms I've tested ... thank you so much for your hard work on this project.
Apache PLC4X, Apache IoTDB and Apache TsFile thank you ... 

... also left a little thank you on your github sponsors page ;-)

**Comment by cowwoc** [comment]
Thanks Chris :) I'm glad it all works.
