### ISSUE TITLE
Inquiry: How to specify additional CMake arguments like `-j 14` or `--verbose`

### ISSUE THREAD

**Issue by beamerblvd** [cmake-maven-project/cmake-maven-project#59]
Perhaps I'm overlooking something obvious in the documentation, but I also consulted the code and still didn't find it.

CMake accepts additional arguments other than those documented for this plugin, including arguments that it passes to the build backend (such as Make).

For example, I might specify `--verbose` when I run `ctest`, or I might specify `-j 14` when I run `cmake --build` in order to have Make run up to 14 (in this example) jobs simultaneously.

Is there a way to specify these, or arbitrary, additional CMake arguments in the `<configuration>`, and I just can't find it? Or is that a missing feature?

Thanks

**Comment by beamerblvd** [comment]
Apologies, I am dumb and didn't connect the example `<option>-DBUILD_THIRDPARTY:bool=on</option>` with doing `<option>--verbose</option>` or `<option>-j</option><option>14</option>`. Please forgive me.

**Comment by cowwoc** [comment]
No worries :)
