### ISSUE TITLE
Support BSD variants (willing to make pull request, but need to be pointed in the right direction)

### ISSUE THREAD

**Issue by beamerblvd** [cmake-maven-project/cmake-maven-project#60]
I'm the author behind [ifaddrs4u](https://github.com/OddSource/ifaddrs4u). The CPP project is compiling successfully (with CMake) on macOS, RHEL, Ubuntu, Windows, and BSD (FreeBSD and NetBSD). When I went to add compilation of the Java project to the workflows, I got this error on all the BSD machines:

```
...
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar (1.0 MB at 2.8 MB/s)
Warning:  Error injecting: com.googlecode.cmakemavenproject.GenerateMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: AssertionError: Unsupported operating system: FreeBSD
...
```

Given that CMake works fine on BSD (all the same commands, etc. as on Linux platforms), I don't see any technical reason why this plugin should exclude BSD from its support. I'm willing to make a pull request to add support, but I'll need to be pointed in the right direction. Is it as simple as changing this method, and then I don't need to do anything else?

https://github.com/cmake-maven-project/cmake-maven-project/blob/7e7929d1330f53cb8d7c1768784ef1acc680a2f8/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L55-L78

FWIW, note that I'm not even using the result of the `getClassifier` method, because I'm using my own profile activation logic to select more precise classifier and set it to a project property:

https://github.com/OddSource/ifaddrs4u/blob/4a9f820e9f155894f3d10248f430e31a39e86203/ifaddrs4j/pom.xml#L404-L561

And then I'm passing that to CMake:

https://github.com/OddSource/ifaddrs4u/blob/4a9f820e9f155894f3d10248f430e31a39e86203/ifaddrs4j/pom.xml#L154

**Comment by beamerblvd** [comment]
I just noticed that https://github.com/cmake-maven-project/cmake-maven-project/issues/56 is a very similar issue, but for architecture vs OS. I, too, will need ARM on Windows, and also on Linux. But I'm confused by: https://github.com/cmake-maven-project/cmake-maven-project/issues/56#issuecomment-1666680043. I thought this Maven plugin was just a pure Java wrapper around CMake, so why would you need to deploy binaries for each supported OS and architecture combo? If I'm missing some native code somewhere, this might present a roadblock to my PR.

**Comment by ksclarke** [comment]
If I'm understanding correctly, I believe that's because the plugin downloads the corresponding version of CMake: https://github.com/cmake-maven-project/cmake-maven-project/blob/master/cmake-binaries-plugin/src/main/java/com/googlecode/cmakemavenproject/GetBinariesMojo.java and @cowwoc was saying to add support the project would have to have tests that test that process works for each of those binaries, which would require a CI environment that supports all the possible supported variations.

**Comment by beamerblvd** [comment]
Ahah. That's what I missed, and I see that the download source doesn't even offer BSD binaries. 

That said, I think there's an easy compromise here. I've been ensuring CMake is available on the path (indeed, I prefer it to use CMake from the path, but that's beside the point here). I'm sure other users of obscure / hard to support OSes or architectures would also prefer to just ensure CMake is on the path rather than having this plugin be impossible to use. So ... why don't we change the error logic so instead of just "Unsupported operating system" or "Unsupported architecture," It's "Unsupported operating system 'xxxx' and CMake is not already available on the PATH?" That way, all OSes and architectures on which CMake can be installed (like BSD, where it can be `pkg install`ed) will enjoy minimal support, but a subset of operating systems will have the first-rate support of additionally providing CMake binaries.

Thoughts?

**Comment by cowwoc** [comment]
Yes, this is the same issue as https://github.com/cmake-maven-project/cmake-maven-project/issues/56

I opted to only support platforms we can build on because I could not run tests on other platforms. That said, I think we should move forward with supporting platforms that we don't have CI for. I just don't have the time to work on it at the moment.

I believe that running binaries off the path is already supported. See https://github.com/cmake-maven-project/cmake-maven-project#using-a-local-cmake-installation

**Comment by cowwoc** [comment]
Sorry, I misread. This issue isn't identical to #56. In that other case, https://cmake.org/download/ provides binaries for us to download but we're missing CI support. In the case of FreeBSD, binaries aren't even available from https://cmake.org/download/.

Try running off the PATH as I mentioned above and let us know if it works.

**Comment by beamerblvd** [comment]
> Try running off the PATH as I mentioned above and let us know if it works.

Doesn't work. I have CMake on the path, and on "supported" platforms, it says, so it definitely can find and use it on the Path:

```
[INFO] Executing cmake on PATH
```

But on "unsupported" Platforms, the plugin fails to load entirely immediately after downloading and never even gets to the point where it tries to find CMake on the path:

```
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/github/cowwoc/pouch/core/3.0/core-3.0.jar (19 kB at 119 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-common/3.25.2-b1/cmake-common-3.25.2-b1.jar (13 kB at 90 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar (247 kB at 1.1 MB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/2.0.0-alpha6/slf4j-api-2.0.0-alpha6.jar (61 kB at 317 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar (1.0 MB at 2.7 MB/s)
Warning:  Error injecting: com.googlecode.cmakemavenproject.GenerateMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: AssertionError: Unsupported operating system: FreeBSD
```

**Comment by beamerblvd** [comment]
And on second look, I don't think that ^^ error is coming from the `getClassifier` method I linked earlier. That method throws an `UnsupportedOperationException`, but that ^^ error is an `AssertionError`. I think it's coming from somewhere else, but I can't find it.

**Comment by cowwoc** [comment]
@beamerblvd That should be easy to fix. In theory, we'd just need to add new enum values, add them into the switch statement, and the rest should work.

I'd love to fix #56 at the same time though since the codebase is already 90% of the way there.

@ksclarke Any chance you have any free cycles? :)

**Comment by beamerblvd** [comment]
Okay, I tracked it down. The `GenerateMojo` extends `CmakeMojo`. `CmakeMojo` has this final anonymously-initialized instance variable:

https://github.com/cmake-maven-project/cmake-maven-project/blob/25a5d95d2d55d57502600683770975b1effb303e/cmake-maven-plugin/src/main/java/com/googlecode/cmakemavenproject/CmakeMojo.java#L51C2-L51C64

That method states that it throws an `AssertionError` for unsupported operating systems, making it impossible to construct any subclass of `CmakeMojo` on unsupported operating systems:

https://github.com/cmake-maven-project/cmake-maven-project/blob/7e7929d1330f53cb8d7c1768784ef1acc680a2f8/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L33-L38

Ultimately, that `AssertionError` is thrown here:

https://github.com/cmake-maven-project/cmake-maven-project/blob/7e7929d1330f53cb8d7c1768784ef1acc680a2f8/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L380-L381

**Comment by cowwoc** [comment]
I have an idea for fixing both these issues. I'll spend a couple of hours today trying to work it out.

**Comment by cowwoc** [comment]
Please try version 3.27.7-b1

**Comment by beamerblvd** [comment]
That did not seem to solve the problem, it just changed it:

```
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar (64 kB at 186 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/googlecode/cmake-maven-project/cmake-common/3.27.7-b1/cmake-common-3.27.7-b1.jar (12 kB at 28 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.24.0/commons-compress-1.24.0.jar (1.1 MB at 3.8 MB/s)
[INFO] Executing cmake on PATH
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.634 s
[INFO] Finished at: 2023-11-05T16:27:53Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.27.7-b1:generate (cmake-generate-ifaddrs4cpp) on project ifaddrs4j: Execution cmake-generate-ifaddrs4cpp of goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.27.7-b1:generate failed: Unsupported platform: FreeBSD/amd64 -> [Help 1]
```

Now it does, at least, try to execute `cmake`, but then I think it gets to the `UnsupportedOperationException` version of the "Unsupported platform" error, instead of the `AssertionError` version of it.

In case you ask, I know for sure that `cmake` is available on the path, because the previous step in the same build runs this:

```
cmake --build ./cmake-external-build --config Release -j 14
```

And that succeeds, which it could only do if `cmake` is on the path. (Also, I believe "[INFO] Executing cmake on PATH" confirms the plugin is finding it on the path.)

**Comment by cowwoc** [comment]
Can you please send me the console output specific to cmake? Separately, try these steps: https://github.com/cmake-maven-project/cmake-maven-project#using-a-local-cmake-installation

**Comment by beamerblvd** [comment]
> Can you please send me the console output specific to cmake? Separately, try these steps: https://github.com/cmake-maven-project/cmake-maven-project#using-a-local-cmake-installation

I already have `<cmake.download>false</...>`:

https://github.com/OddSource/ifaddrs4u/blame/main/ifaddrs4j/pom.xml#L64

Setting `cmake.dir` is tricker, because it's not in the same place on every platform, and I'm dealing with macOS, RH, Debian, BSD, *and* Windows. I've been relying on ensuring that it's present on the path specifically so that I don't have to do that. Getting its full path into Maven at initialization time is trickier. But I can try to do that if you think it's the only way.

The output I posted above is everything that the plugin is giving me, but on the understanding that I don't know exactly what you're asking for, here's the Workflow run with the full output: https://github.com/OddSource/ifaddrs4u/actions/runs/6762399825/job/18378326536
