### ISSUE TITLE
linux-ARM_64 Supported?

### ISSUE THREAD

**Issue by YZSPSJK** [cmake-maven-project/cmake-maven-project#67]
does is suppert linux-arm_64?
if it does, how can i configure my 'pom.xml' file

thank you

**Comment by cowwoc** [comment]
Hi @YZSPSJK

Yes, if you use the plugins mentioned in the readme, Maven should select the `linux-arm_64` platform and download the right binaries.

**Comment by YZSPSJK** [comment]
@cowwoc 
here is my pom.xml conf

`<groupId>com.googlecode.cmake-maven-project</groupId>
                <artifactId>cmake-maven-plugin</artifactId>
                <version>3.27.7-b1</version>
`

by  command  `mvn install`
the result get error
`[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.27.7-b1:generate (cmake-generate) on project GmSSLJNI: Unable to find/resolve artifact.: The following artifacts could not be resolved: com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.27.7-b1 (absent): Could not find artifact com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.27.7-b1 in alimaven (https://maven.aliyun.com/repository/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by ksclarke** [comment]
Try a newer version. The `3.27.7-b1` release doesn't have linux-arm support, but `3.30.2-b1` does: Cf. https://repo1.maven.org/maven2/com/googlecode/cmake-maven-project/cmake-binaries/3.30.2-b1/

**Comment by YZSPSJK** [comment]
@ksclarke 
it  works!    thanks!
