### ISSUE TITLE
Generator Required?

### ISSUE THREAD

**Issue by msteinbeck** [cmake-maven-project/cmake-maven-project#7]
I would like to use this lib without the requirement of setting a specific generator. The reason is, that I actually don't know what kind of environment and compiler the user has. This lib does not depend on an actual generator anyway because it uses `--build` and `--target` to compile the project.

**Comment by cowwoc** [comment]
@retuxx What configuration are you passing into the plugin that it gives you an error about requiring a specific generator? It would also help if you could include the error message.

**Comment by msteinbeck** [comment]
Sorry for not responding. I would like to avoid setting the actual generator with the `generator` attribute as CMake will automatically choose one. Unfortunately, when leaving the attribute I get the following error:

```bash
The parameters 'generator' for goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.4.1-b1:generate are missing or invalid -> [Help 1]
```

By requiring the `generator` attribute, I can't make my script os independent because whatever generator I use it will not be available on any os. For instance, currently I'm using `Unix Makefiles` but when a Windows user tries to run the maven script it fails as `Unix Makefiles` are not available on Windows. Usually, one can leave out the generator letting CMake choose the one to take.

**Comment by cowwoc** [comment]
@msteinbeck The way I've handled this is to define one Maven profile per platform, have each profile set a property indicating the cmake generator to use, then have the shared instance of cmake-maven-plugin use the generator indicated by that property.

That said, I understand the benefit of letting cmake choose. For example, your code might depend on Visual Studio 2015 today and 2017 tomorrow. Ideally you don't want to hard-code a generator in the build.

I'll try adding this functionality in an upcoming release.

**Comment by tresf** [comment]
>  I understand the benefit of letting cmake choose. For example, your code might depend on Visual Studio 2015 today and 2017 tomorrow. Ideally you don't want to hard-code a generator in the build.

Exactly!  CMake seems to handle the generators sanely 99% of the time. I'd be a big fan of this feature.

**Comment by cowwoc** [comment]
I finally got around to working on this feature (sorry for the insane wait!)

**Comment by msteinbeck** [comment]
Thank you for adding this feature.
