### ISSUE TITLE
cmake-binaries-3.4.1-b1-linux32.jar contains x64 binaries

### ISSUE THREAD

**Issue by rogeriorc** [cmake-maven-project/cmake-maven-project#8]
The plugin fails when executing on Linux 32 bits.

Error message: .../target/dependency/cmake/bin/cmake: cannot execute binary file

> objdump -a cmake
> 
> cmake:     file format elf64-x86-64

**Comment by ksclarke** [comment]
Sorry about that. I believe I've fixed this now (and it's made it's way into Maven Central). I didn't bump the version number though because it was a build error rather than a code problem. Would you try again? You might have to clear the jar from your local Maven file system cache first though.

**Comment by rogeriorc** [comment]
I tested today and worked!
Thanks!

**Comment by ksclarke** [comment]
Great, thanks for confirming!
